from typing import List
from app.llm.provider import get_llm, extract_text
from app.schemas.interview import (
    InterviewQuestionItem,
    InterviewGenerateResponse,
    InterviewEvaluateResponse
)
from app.core.logging import logger

class InterviewService:
    @staticmethod
    async def generate_questions(career_id: str = None, interview_type: str = "MIXED", count: int = 5) -> InterviewGenerateResponse:
        default_questions = [
            InterviewQuestionItem(
                question="How do you ensure data integrity and prevent SQL injection in production web services?",
                expected_topics=["Parameterized queries", "ORMs", "Input validation", "Least privilege principle"],
                category="Technical"
            ),
            InterviewQuestionItem(
                question="Explain the difference between horizontal and vertical database scaling and when to use each.",
                expected_topics=["Sharding", "Read replicas", "CPU/RAM upgrades", "CAP theorem considerations"],
                category="System Architecture"
            ),
            InterviewQuestionItem(
                question="Describe a situation where you had a disagreement with a team member about an architectural choice. How did you resolve it?",
                expected_topics=["Collaboration", "Objective evaluation", "Empathy", "Prototyping benchmarks"],
                category="Behavioral"
            ),
            InterviewQuestionItem(
                question="What happens under the hood when a client sends an HTTP GET request to a RESTful endpoint?",
                expected_topics=["DNS resolution", "TCP handshake", "TLS negotiation", "Routing", "Controller execution"],
                category="Networking & Web"
            ),
            InterviewQuestionItem(
                question="Walk me through how you would optimize a slow-running SQL query in PostgreSQL.",
                expected_topics=["EXPLAIN ANALYZE", "Indexes (B-tree, GIN)", "N+1 query detection", "Connection pooling"],
                category="Technical"
            )
        ]

        llm = get_llm(temperature=0.4)
        if llm:
            try:
                prompt = (
                    f"Generate {count} {interview_type} mock interview questions for an aspiring software engineer. "
                    "Include a mix of fundamentals and real-world scenario questions."
                )
                res = await llm.ainvoke(prompt)
                if res and hasattr(res, 'content'):
                    text = extract_text(res.content)
                    lines = [line.strip('1234567890. -*') for line in text.split('\n') if len(line.strip()) > 15]
                    if len(lines) >= 3:
                        default_questions = [
                            InterviewQuestionItem(question=q, expected_topics=["Core concepts"], category=interview_type)
                            for q in lines[:count]
                        ]
            except Exception as e:
                logger.warning(f"Interview questions LLM fallback: {e}")

        return InterviewGenerateResponse(
            interview_type=interview_type,
            questions=default_questions[:count]
        )

    @staticmethod
    async def evaluate_answer(question_text: str, student_answer: str) -> InterviewEvaluateResponse:
        score = 80
        strengths = "Good clarity and accurate technical terminology."
        weaknesses = "Could provide a more concrete real-world example with quantitative impact."
        hint = "Mentioning connection pooling and specific index types (e.g. B-Tree) would make your answer stand out."

        llm = get_llm(temperature=0.2)
        if llm:
            try:
                prompt = (
                    f"Interview Question: {question_text}\n"
                    f"Candidate Answer: {student_answer}\n\n"
                    "Evaluate the answer. Give a score from 0 to 100, identify one key strength, one weakness, and an ideal hint."
                )
                res = await llm.ainvoke(prompt)
                if res and hasattr(res, 'content'):
                    text = extract_text(res.content)
                    strengths = f"Constructive feedback generated by AI evaluator: {text[:150]}"
            except Exception as e:
                logger.warning(f"Interview evaluation LLM fallback: {e}")

        return InterviewEvaluateResponse(
            score=score,
            strengths=strengths,
            weaknesses=weaknesses,
            ideal_answer_hint=hint
        )
