import { 
  StudentProfile, 
  Skill, 
  StudentSkill, 
  Career, 
  Course, 
  Job, 
  Application, 
  ResumeAnalysis,
  InterviewSession,
  InterviewReport
} from '../types';

export const INITIAL_STUDENT_PROFILE: StudentProfile = {
  id: 'std-2026-001',
  user_id: 'usr-student-001',
  first_name: 'Alexandria',
  last_name: 'Vance',
  phone: '+1 (555) 739-2810',
  city: 'Boston',
  state: 'Massachusetts',
  country: 'United States',
  bio: 'Computer Science senior with an obsession for fault-tolerant distributed protocols, high-throughput message streams, and system internals.',
  linkedin_url: 'https://linkedin.com/in/alexandriavance',
  github_url: 'https://github.com/alexandriavance',
  portfolio_url: 'https://alexvance.engineer',
  readiness_score: 84,
};

export const MASTER_SKILLS: Skill[] = [
  { id: 'sk-1', name: 'Python', category: 'Programming Languages' },
  { id: 'sk-2', name: 'TypeScript', category: 'Programming Languages' },
  { id: 'sk-3', name: 'Go', category: 'Programming Languages' },
  { id: 'sk-4', name: 'Rust', category: 'Programming Languages' },
  { id: 'sk-5', name: 'PostgreSQL', category: 'Databases & Storage' },
  { id: 'sk-6', name: 'Redis', category: 'Databases & Storage' },
  { id: 'sk-7', name: 'Docker', category: 'Cloud & DevOps' },
  { id: 'sk-8', name: 'Kubernetes', category: 'Cloud & DevOps' },
  { id: 'sk-9', name: 'Apache Kafka', category: 'Distributed Systems' },
  { id: 'sk-10', name: 'React', category: 'Frontend Development' },
  { id: 'sk-11', name: 'FastAPI', category: 'Backend Frameworks' },
  { id: 'sk-12', name: 'GraphQL', category: 'APIs & Protocols' },
];

export const INITIAL_STUDENT_SKILLS: StudentSkill[] = [
  {
    id: 'ssk-1',
    skill_id: 'sk-1',
    skill_name: 'Python',
    category: 'Programming Languages',
    proficiency: 'EXPERT',
    source: 'ASSESSMENT',
    years_experience: 3,
    is_verified: true,
  },
  {
    id: 'ssk-2',
    skill_id: 'sk-2',
    skill_name: 'TypeScript',
    category: 'Programming Languages',
    proficiency: 'ADVANCED',
    source: 'ASSESSMENT',
    years_experience: 2,
    is_verified: true,
  },
  {
    id: 'ssk-3',
    skill_id: 'sk-5',
    skill_name: 'PostgreSQL',
    category: 'Databases & Storage',
    proficiency: 'ADVANCED',
    source: 'RESUME_PARSED',
    years_experience: 2,
    is_verified: true,
  },
  {
    id: 'ssk-4',
    skill_id: 'sk-7',
    skill_name: 'Docker',
    category: 'Cloud & DevOps',
    proficiency: 'INTERMEDIATE',
    source: 'SELF_REPORTED',
    years_experience: 1,
    is_verified: false,
  },
  {
    id: 'ssk-5',
    skill_id: 'sk-6',
    skill_name: 'Redis',
    category: 'Databases & Storage',
    proficiency: 'BEGINNER',
    source: 'SELF_REPORTED',
    years_experience: 1,
    is_verified: false,
  },
];

export const CAREER_TRACKS: Career[] = [
  {
    id: 'car-1',
    title: 'Distributed Backend Engineer',
    description: 'Architects fault-tolerant, high-throughput microservice backends, database clusters, and low-latency API layers.',
    average_salary_min: 115000,
    average_salary_max: 185000,
    demand_level: 'Very High',
    skills: [
      { skill_name: 'Python', importance: 'CRITICAL', required_proficiency: 'ADVANCED', weight: 3.0 },
      { skill_name: 'PostgreSQL', importance: 'CRITICAL', required_proficiency: 'ADVANCED', weight: 3.0 },
      { skill_name: 'Docker', importance: 'CRITICAL', required_proficiency: 'ADVANCED', weight: 2.5 },
      { skill_name: 'Redis', importance: 'IMPORTANT', required_proficiency: 'INTERMEDIATE', weight: 2.0 },
      { skill_name: 'Kubernetes', importance: 'IMPORTANT', required_proficiency: 'INTERMEDIATE', weight: 2.0 },
      { skill_name: 'Apache Kafka', importance: 'NICE_TO_HAVE', required_proficiency: 'BEGINNER', weight: 1.5 },
    ],
  },
  {
    id: 'car-2',
    title: 'Cloud & DevOps Architect',
    description: 'Automates infrastructure as code, CI/CD orchestration, telemetry, zero-trust cloud security, and cluster autoscaling.',
    average_salary_min: 120000,
    average_salary_max: 195000,
    demand_level: 'Very High',
    skills: [
      { skill_name: 'Docker', importance: 'CRITICAL', required_proficiency: 'EXPERT', weight: 3.0 },
      { skill_name: 'Kubernetes', importance: 'CRITICAL', required_proficiency: 'ADVANCED', weight: 3.0 },
      { skill_name: 'Go', importance: 'IMPORTANT', required_proficiency: 'INTERMEDIATE', weight: 2.0 },
      { skill_name: 'Python', importance: 'IMPORTANT', required_proficiency: 'INTERMEDIATE', weight: 2.0 },
    ],
  },
  {
    id: 'car-3',
    title: 'Machine Learning & AI Platform Engineer',
    description: 'Productionizes foundation models, vector embeddings, GPU acceleration pipelines, and semantic RAG inference nodes.',
    average_salary_min: 130000,
    average_salary_max: 210000,
    demand_level: 'High',
    skills: [
      { skill_name: 'Python', importance: 'CRITICAL', required_proficiency: 'EXPERT', weight: 3.0 },
      { skill_name: 'FastAPI', importance: 'CRITICAL', required_proficiency: 'ADVANCED', weight: 2.5 },
      { skill_name: 'Docker', importance: 'IMPORTANT', required_proficiency: 'INTERMEDIATE', weight: 2.0 },
      { skill_name: 'PostgreSQL', importance: 'IMPORTANT', required_proficiency: 'INTERMEDIATE', weight: 2.0 },
    ],
  },
];

export const PLATFORM_COURSES: Course[] = [
  {
    id: 'crs-1',
    title: 'Hardened Distributed Systems & Concurrency',
    provider: 'Campus2Corporate Academy',
    url: '#',
    description: 'Master consensus algorithms, distributed locking in Redis, and optimistic concurrency in Postgres.',
    difficulty: 'ADVANCED',
    duration_hours: 28,
    is_free: true,
    price: 'Free (Scholarship)',
    rating: 4.95,
    skills: ['Python', 'PostgreSQL', 'Redis'],
  },
  {
    id: 'crs-2',
    title: 'Kubernetes in Production: Fleet Orchestration',
    provider: 'Campus2Corporate Academy',
    url: '#',
    description: 'Helm charts, zero-downtime rolling upgrades, ingress controllers, and private cluster security.',
    difficulty: 'ADVANCED',
    duration_hours: 32,
    is_free: false,
    price: '$79.00',
    rating: 4.88,
    skills: ['Kubernetes', 'Docker'],
  },
  {
    id: 'crs-3',
    title: 'Modern TypeScript & Micro-Frontend Architecture',
    provider: 'Platform Internal',
    url: '#',
    description: 'Strict type invariants, AST metaprogramming, state machines, and bundler compilation.',
    difficulty: 'INTERMEDIATE',
    duration_hours: 20,
    is_free: true,
    price: 'Free',
    rating: 4.9,
    skills: ['TypeScript', 'React'],
  },
];

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-101',
    title: 'Staff Distributed Systems Engineer',
    company_name: 'Vanguard Systems Ledger',
    company_logo: '🏛️',
    location: 'Boston, MA',
    work_mode: 'HYBRID',
    employment_type: 'FULL_TIME',
    salary_min: 145000,
    salary_max: 185000,
    experience_min: 2,
    experience_max: 5,
    description: 'Seeking an exceptional engineer to construct transaction-safe settlement protocols handling 50k ops/sec.',
    posted_at: '2 days ago',
    skills: [
      { skill_name: 'Python', weight: 3.0, required_proficiency: 'ADVANCED', is_required: true },
      { skill_name: 'PostgreSQL', weight: 3.0, required_proficiency: 'ADVANCED', is_required: true },
      { skill_name: 'Docker', weight: 2.0, required_proficiency: 'INTERMEDIATE', is_required: true },
      { skill_name: 'Redis', weight: 2.0, required_proficiency: 'INTERMEDIATE', is_required: false },
    ],
  },
  {
    id: 'job-102',
    title: 'Junior Cloud Infrastructure Fellow',
    company_name: 'Aether Cloud Consortium',
    company_logo: '☁️',
    location: 'Remote',
    work_mode: 'REMOTE',
    employment_type: 'INTERNSHIP',
    salary_min: 75000,
    salary_max: 95000,
    experience_min: 0,
    experience_max: 2,
    description: 'Join our cloud platform guild: maintain Terraform modules, container registries, and edge telemetry.',
    posted_at: '1 day ago',
    skills: [
      { skill_name: 'Docker', weight: 3.0, required_proficiency: 'INTERMEDIATE', is_required: true },
      { skill_name: 'Kubernetes', weight: 2.0, required_proficiency: 'BEGINNER', is_required: false },
      { skill_name: 'TypeScript', weight: 1.5, required_proficiency: 'BEGINNER', is_required: false },
    ],
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app-501',
    job_id: 'job-101',
    job_title: 'Staff Distributed Systems Engineer',
    company_name: 'Vanguard Systems Ledger',
    status: 'INTERVIEW_SCHEDULED',
    applied_at: 'September 24, 2026',
    match_score: 91,
    notes: 'Candidate demonstrates strong PostgreSQL row-level locks and Python mastery.',
    match_breakdown: {
      score: 91,
      matched_count: 3,
      total_skills: 4,
      matched_skills: [
        { skill_name: 'Python', required_proficiency: 'ADVANCED', student_proficiency: 'EXPERT', is_verified: true },
        { skill_name: 'PostgreSQL', required_proficiency: 'ADVANCED', student_proficiency: 'ADVANCED', is_verified: true },
        { skill_name: 'Docker', required_proficiency: 'INTERMEDIATE', student_proficiency: 'INTERMEDIATE', is_verified: false },
      ],
      missing_skills: [
        { skill_name: 'Redis', is_required: false },
      ],
    },
    status_history: [
      {
        from_status: null,
        to_status: 'APPLIED',
        changed_by: 'Alexandria Vance',
        role: 'STUDENT',
        notes: 'Submitted portfolio dossier and resume.',
        timestamp: '2026-09-24T10:15:00Z',
      },
      {
        from_status: 'APPLIED',
        to_status: 'REVIEWING',
        changed_by: 'Hiring Committee',
        role: 'RECRUITER',
        notes: 'High academic GPA and verified Python badge verified.',
        timestamp: '2026-09-25T14:30:00Z',
      },
      {
        from_status: 'REVIEWING',
        to_status: 'INTERVIEW_SCHEDULED',
        changed_by: 'Hiring Committee',
        role: 'RECRUITER',
        notes: 'Technical panel interview scheduled with Senior Principal Architect.',
        timestamp: '2026-09-27T09:00:00Z',
      },
    ],
  },
];

export const MOCK_RESUME_ANALYSIS: ResumeAnalysis = {
  file_name: 'Alexandria_Vance_Dossier_2026.pdf',
  uploaded_at: 'September 28, 2026',
  overall_score: 87,
  ats_score: 92,
  extracted_skills: ['Python', 'PostgreSQL', 'Docker', 'TypeScript', 'FastAPI', 'Redis', 'Git'],
  missing_skills: ['Kubernetes (Required for Senior Bands)', 'Prometheus Telemetry', 'gRPC Protocol Buffers'],
  strengths: [
    'Exemplary quantifiable impact metrics (e.g. "Reduced query latency by 42% on 10M rows")',
    'Clean, single-column skeuomorphic typography easily parsed by modern ATS parsers',
    'Explicit project links referencing verified live endpoints and code reviews',
  ],
  improvements: [
    'Add production Kubernetes manifest deployment experience under the Cloud Resume section',
    'Include distributed tracing methodologies (OpenTelemetry / Jaeger) in backend bullet points',
  ],
};
