import React, { useState } from 'react';
import { PaperCard, BrassPlaque, RubberStamp, WaxSeal } from '../../components/common/SkeuoElements';
import { Map, CheckSquare, Square, Calendar, Sparkles, Download } from 'lucide-react';

interface Milestone {
  month: number;
  title: string;
  theme: string;
  tasks: { id: string; text: string; done: boolean }[];
  capstone: string;
}

export const CareerRoadmapPage: React.FC = () => {
  const [duration, setDuration] = useState<'3_MONTH' | '6_MONTH'>('3_MONTH');
  const [milestones, setMilestones] = useState<Milestone[]>([
    {
      month: 1,
      title: 'Month 1: Storage Layer & Relational Hardening',
      theme: 'PostgreSQL ACID Internals & Redis Distributed Locking',
      tasks: [
        { id: 't1', text: 'Implement PostgreSQL row-level advisory locking (SELECT FOR UPDATE) on ledger accounts', done: true },
        { id: 't2', text: 'Configure Redis Sentinel cluster with Redlock mutual exclusion algorithm', done: true },
        { id: 't3', text: 'Benchmark 100k writes/sec using Connection Pooling with PgBouncer', done: false },
      ],
      capstone: 'Build a distributed double-entry financial ledger service handling concurrent transfers.',
    },
    {
      month: 2,
      title: 'Month 2: Containerization & Cloud Fleet Orchestration',
      theme: 'Multi-Stage Docker Builds & Kubernetes Ingress Control',
      tasks: [
        { id: 't4', text: 'Write hardened scratch/alpine multi-stage Dockerfiles reducing image size < 35MB', done: false },
        { id: 't5', text: 'Deploy stateful sets and persistent volume claims for Redis cluster in Minikube', done: false },
        { id: 't6', text: 'Implement zero-downtime rolling deployment strategies and readiness probes', done: false },
      ],
      capstone: 'Deploy an autoscaling Kubernetes cluster with automated Prometheus health alerts.',
    },
    {
      month: 3,
      title: 'Month 3: Asynchronous Event Streaming & Mock Trials',
      theme: 'Apache Kafka Partitioning & Technical Mock Interview Mastery',
      tasks: [
        { id: 't7', text: 'Architect consumer groups with manual offset commits and dead-letter queues', done: false },
        { id: 't8', text: 'Complete 3 AI Mock Interview simulations on Distributed Consensus', done: false },
        { id: 't9', text: 'Polish Resume ATS metrics with quantified throughput benchmarks', done: false },
      ],
      capstone: 'Final End-to-End Enterprise Architecture Portfolio Dossier ready for recruiter submission.',
    },
  ]);

  const toggleTask = (monthIdx: number, taskId: string) => {
    setMilestones((prev) =>
      prev.map((m, idx) => {
        if (idx !== monthIdx) return m;
        return {
          ...m,
          tasks: m.tasks.map((t) => (t.id === taskId ? { ...t, done: !t.done } : t)),
        };
      })
    );
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* Plaque Banner */}
      <div
        className="wood-frame"
        style={{
          padding: '18px 24px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: '12px',
        }}
      >
        <div>
          <h1 style={{ fontSize: '26px', margin: 0, color: '#2b1a03' }}>
            LangGraph Synthesized Career Roadmap
          </h1>
          <p style={{ margin: 0, fontSize: '14px', color: 'var(--ink-faded)', fontStyle: 'italic' }}>
            Adaptive milestone journey generated by Gemini 3.5 Flash Lite based on your target role gaps.
          </p>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <button
            onClick={() => setDuration('3_MONTH')}
            className={duration === '3_MONTH' ? 'btn-brass' : 'btn-paper'}
            style={{ fontSize: '13px', padding: '6px 12px' }}
          >
            3-Month Sprint
          </button>
          <button
            onClick={() => setDuration('6_MONTH')}
            className={duration === '6_MONTH' ? 'btn-brass' : 'btn-paper'}
            style={{ fontSize: '13px', padding: '6px 12px' }}
          >
            6-Month Masterclass
          </button>
        </div>
      </div>

      {/* Timeline Stream */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
        {milestones.map((m, mIdx) => (
          <PaperCard key={m.month} stitched style={{ position: 'relative' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '1px solid #d4be94', paddingBottom: '12px', marginBottom: '14px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                <WaxSeal letter={`M${m.month}`} size="sm" />
                <div>
                  <h3 style={{ margin: 0, fontSize: '18px' }}>{m.title}</h3>
                  <span style={{ fontSize: '13px', color: 'var(--ink-faded)', fontStyle: 'italic' }}>
                    Focus: {m.theme}
                  </span>
                </div>
              </div>

              <RubberStamp
                label={m.tasks.every((t) => t.done) ? 'COMPLETED' : 'IN PROGRESS'}
                variant={m.tasks.every((t) => t.done) ? 'verified' : 'crimson'}
                rotate={1}
              />
            </div>

            {/* Checklist Tasks */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', marginBottom: '16px' }}>
              {m.tasks.map((task) => (
                <div
                  key={task.id}
                  onClick={() => toggleTask(mIdx, task.id)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '10px',
                    cursor: 'pointer',
                    padding: '8px 12px',
                    background: task.done ? 'rgba(36, 88, 59, 0.08)' : '#fbf6e8',
                    borderRadius: '4px',
                    border: '1px solid #dcd0b7',
                  }}
                >
                  {task.done ? (
                    <CheckSquare size={18} color="var(--ink-stamp-green)" />
                  ) : (
                    <Square size={18} color="var(--ink-muted)" />
                  )}
                  <span
                    style={{
                      fontSize: '14px',
                      color: task.done ? 'var(--ink-muted)' : 'var(--ink-primary)',
                      textDecoration: task.done ? 'line-through' : 'none',
                    }}
                  >
                    {task.text}
                  </span>
                </div>
              ))}
            </div>

            {/* Capstone Challenge */}
            <div
              style={{
                background: '#f5ead2',
                borderLeft: '4px solid #b8860b',
                padding: '10px 14px',
                borderRadius: '0 4px 4px 0',
                fontSize: '13px',
              }}
            >
              <strong>Capstone Milestone Artifact:</strong> {m.capstone}
            </div>
          </PaperCard>
        ))}
      </div>
    </div>
  );
};
