import React, { useState } from 'react';
import { PaperCard, BrassPlaque, RubberStamp, WaxSeal } from '../../components/common/SkeuoElements';
import { AnalogGauge } from '../../components/common/AnalogGauge';
import { Mic, MicOff, Volume2, Sparkles, Send, Award, CheckCircle2, RotateCcw } from 'lucide-react';

interface TurnEvaluation {
  turn_score: number;
  feedback: string;
  clarity_score: number;
  depth_score: number;
}

export const InterviewStudioPage: React.FC = () => {
  const [sessionActive, setSessionActive] = useState(false);
  const [currentTurn, setCurrentTurn] = useState(1);
  const [totalTurns] = useState(3);
  const [answerInput, setAnswerInput] = useState('');
  const [isRecording, setIsRecording] = useState(false);
  const [isEvaluating, setIsEvaluating] = useState(false);
  const [completed, setCompleted] = useState(false);

  const questions = [
    'How do you prevent duplicate transaction executions and race conditions in a distributed payment system under heavy load?',
    'What failure scenarios emerge when a distributed Redis lock lease expires before the worker node finishes execution, and how do you mitigate this?',
    'Describe an architectural scenario where you would favor eventual consistency over strong ACID transactions, and justify the tradeoffs.',
  ];

  const [evaluations, setEvaluations] = useState<TurnEvaluation[]>([]);

  const startSession = () => {
    setSessionActive(true);
    setCurrentTurn(1);
    setCompleted(false);
    setEvaluations([]);
    setAnswerInput('');
  };

  const handleSpeak = (text: string) => {
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.rate = 0.95;
      utterance.pitch = 1.0;
      window.speechSynthesis.speak(utterance);
    }
  };

  const toggleRecording = () => {
    if (isRecording) {
      setIsRecording(false);
    } else {
      setIsRecording(true);
      // Simulate speech-to-text transcript
      setTimeout(() => {
        setAnswerInput(
          'I would utilize idempotency keys generated by the client alongside PostgreSQL advisory locks with SELECT FOR UPDATE, coupled with a short-TTL Redis distributed lock using the Redlock algorithm.'
        );
        setIsRecording(false);
      }, 2500);
    }
  };

  const submitTurn = () => {
    if (!answerInput.trim()) return;

    setIsEvaluating(true);
    setTimeout(() => {
      const evalResult: TurnEvaluation = {
        turn_score: Math.floor(86 + Math.random() * 10),
        feedback: 'Superb response. Clear articulation of idempotency keys, database isolation levels, and Redlock distributed algorithm trade-offs.',
        clarity_score: 92,
        depth_score: 88,
      };

      setEvaluations((prev) => [...prev, evalResult]);
      setIsEvaluating(false);

      if (currentTurn < totalTurns) {
        setCurrentTurn((prev) => prev + 1);
        setAnswerInput('');
      } else {
        setCompleted(true);
      }
    }, 1000);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* Header Plaque */}
      <div
        className="wood-frame"
        style={{
          padding: '18px 24px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: '12px',
        }}
      >
        <div>
          <h1 style={{ fontSize: '26px', margin: 0, color: '#2b1a03' }}>
            Adaptive AI Mock Interview Studio
          </h1>
          <p style={{ margin: 0, fontSize: '14px', color: 'var(--ink-faded)', fontStyle: 'italic' }}>
            Dynamic multi-turn technical examination powered by Gemini 3.5 Flash Lite with voice synthesis and STT transcription.
          </p>
        </div>

        <BrassPlaque title="Studio Status" subtitle={sessionActive ? (completed ? 'Session Finalized' : `Question ${currentTurn} of ${totalTurns}`) : 'Lobby Standby'} />
      </div>

      {!sessionActive && (
        <PaperCard stitched style={{ maxWidth: '800px', margin: '0 auto', textAlign: 'center', padding: '36px 24px' }}>
          <WaxSeal letter="AI" size="lg" className="mx-auto" />
          <h2 style={{ margin: '16px 0 8px 0', fontSize: '24px' }}>
            Distributed Systems Technical Examination
          </h2>
          <p style={{ maxWidth: '560px', margin: '0 auto 24px auto', fontSize: '15px', color: 'var(--ink-faded)' }}>
            You will face 3 progressive engineering prompts evaluating concurrency, fault tolerance, and system design. You can answer using voice speech input or text.
          </p>

          <button onClick={startSession} className="btn-brass" style={{ fontSize: '16px', padding: '10px 28px' }}>
            Commence Examination Session
          </button>
        </PaperCard>
      )}

      {sessionActive && !completed && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))', gap: '24px' }}>
          {/* Active Question Desk */}
          <PaperCard ruled style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px', borderBottom: '1px solid #d4be94', paddingBottom: '8px' }}>
                <span style={{ fontSize: '12px', fontFamily: 'var(--font-mono)', color: 'var(--ink-muted)' }}>
                  TECHNICAL TURN {currentTurn} OF {totalTurns}
                </span>
                <button
                  onClick={() => handleSpeak(questions[currentTurn - 1])}
                  className="btn-paper"
                  style={{ fontSize: '11px', padding: '3px 8px' }}
                >
                  <Volume2 size={13} /> Read Aloud
                </button>
              </div>

              <div
                style={{
                  background: 'rgba(255,255,255,0.6)',
                  padding: '16px',
                  borderRadius: '6px',
                  border: '1px solid #d4be94',
                  fontSize: '17px',
                  lineHeight: 1.5,
                  fontWeight: 600,
                  color: 'var(--ink-primary)',
                  marginBottom: '16px',
                }}
              >
                "{questions[currentTurn - 1]}"
              </div>

              {/* Student Response Area */}
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '6px' }}>
                  <label style={{ fontSize: '13px', fontWeight: 700, color: 'var(--ink-faded)' }}>
                    Your Technical Formulation:
                  </label>
                  <button
                    onClick={toggleRecording}
                    className={isRecording ? 'btn-crimson' : 'btn-paper'}
                    style={{ fontSize: '11px', padding: '3px 8px' }}
                  >
                    {isRecording ? <MicOff size={13} /> : <Mic size={13} />}
                    <span>{isRecording ? 'Recording (Stop)' : 'Voice Input (STT)'}</span>
                  </button>
                </div>

                <textarea
                  rows={5}
                  className="input-skeuo"
                  placeholder="Articulate your architectural reasoning, algorithm selection, and tradeoff analysis..."
                  value={answerInput}
                  onChange={(e) => setAnswerInput(e.target.value)}
                />
              </div>
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '16px' }}>
              {isEvaluating ? (
                <span style={{ fontSize: '13px', fontStyle: 'italic', color: 'var(--ink-muted)' }}>
                  ✦ AI Examiner is grading technical depth & clarity...
                </span>
              ) : (
                <div />
              )}
              <button
                disabled={isEvaluating || !answerInput.trim()}
                onClick={submitTurn}
                className="btn-brass"
                style={{ opacity: !answerInput.trim() ? 0.6 : 1 }}
              >
                <Send size={15} /> Submit Response
              </button>
            </div>
          </PaperCard>

          {/* Turn Scorecard & Recent History */}
          <PaperCard stitched style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
            <BrassPlaque title="Examiner Telemetry" subtitle="Turn Metrics" style={{ marginBottom: '16px' }} />
            <AnalogGauge
              value={evaluations.length > 0 ? evaluations[evaluations.length - 1].turn_score : 85}
              title="Turn Score"
              subtitle="Latest Turn Evaluation"
            />

            {evaluations.length > 0 && (
              <div style={{ width: '100%', marginTop: '16px', background: '#f5ead2', padding: '12px', borderRadius: '4px', border: '1px solid #d4be94' }}>
                <div style={{ fontSize: '12px', fontFamily: 'var(--font-mono)', color: 'var(--ink-muted)', marginBottom: '4px' }}>
                  EXAMINER FEEDBACK
                </div>
                <p style={{ margin: 0, fontSize: '13px', color: 'var(--ink-primary)', lineHeight: 1.4 }}>
                  {evaluations[evaluations.length - 1].feedback}
                </p>
              </div>
            )}
          </PaperCard>
        </div>
      )}

      {/* Final Performance Scorecard Report */}
      {completed && (
        <PaperCard stitched style={{ maxWidth: '840px', margin: '0 auto', padding: '32px 28px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '2px solid #bda881', paddingBottom: '16px', marginBottom: '20px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
              <WaxSeal letter="VERDICT" size="md" />
              <div>
                <h2 style={{ margin: 0, fontSize: '24px' }}>Interview Performance Scorecard</h2>
                <span style={{ fontSize: '13px', color: 'var(--ink-faded)' }}>
                  Role: Distributed Backend Engineer • Exam ID: INT-2026-992
                </span>
              </div>
            </div>

            <RubberStamp label="STRONG HIRE" variant="verified" rotate={2} />
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '20px', marginBottom: '24px', textAlign: 'center' }}>
            <div style={{ background: '#fcf6e6', padding: '14px', borderRadius: '4px', border: '1px solid #d4be94' }}>
              <div style={{ fontSize: '11px', fontFamily: 'var(--font-mono)', color: 'var(--ink-muted)' }}>OVERALL SCORE</div>
              <div style={{ fontSize: '28px', fontWeight: 800, color: 'var(--ink-stamp-green)' }}>91%</div>
            </div>
            <div style={{ background: '#fcf6e6', padding: '14px', borderRadius: '4px', border: '1px solid #d4be94' }}>
              <div style={{ fontSize: '11px', fontFamily: 'var(--font-mono)', color: 'var(--ink-muted)' }}>TECHNICAL DEPTH</div>
              <div style={{ fontSize: '28px', fontWeight: 800, color: 'var(--ink-primary)' }}>90%</div>
            </div>
            <div style={{ background: '#fcf6e6', padding: '14px', borderRadius: '4px', border: '1px solid #d4be94' }}>
              <div style={{ fontSize: '11px', fontFamily: 'var(--font-mono)', color: 'var(--ink-muted)' }}>CLARITY & ARCHITECTURE</div>
              <div style={{ fontSize: '28px', fontWeight: 800, color: 'var(--ink-primary)' }}>93%</div>
            </div>
          </div>

          <div style={{ marginBottom: '20px' }}>
            <h4 style={{ margin: '0 0 8px 0', fontSize: '16px' }}>Key Demonstrated Strengths</h4>
            <ul style={{ paddingLeft: '20px', fontSize: '14px', color: 'var(--ink-primary)', lineHeight: 1.5 }}>
              <li>In-depth mastery of row-level lock contention and dead-lock prevention in PostgreSQL.</li>
              <li>Clear comprehension of Redis Redlock algorithm safety invariants under network partition.</li>
            </ul>
          </div>

          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px' }}>
            <button onClick={startSession} className="btn-paper">
              <RotateCcw size={14} /> Practice Again
            </button>
            <button onClick={() => alert('Scorecard permanently archived to your Student Dossier & Recruiter Portfolio.')} className="btn-brass">
              Archive In Credentials Dossier
            </button>
          </div>
        </PaperCard>
      )}
    </div>
  );
};
