-- Migration: 005_backend_rls_alignment.sql
-- Description: Disables RLS for tables managed exclusively via backend API Gateway to allow full service-level operations

BEGIN;

ALTER TABLE students DISABLE ROW LEVEL SECURITY;
ALTER TABLE student_education DISABLE ROW LEVEL SECURITY;
ALTER TABLE academic_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE student_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE certifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE certification_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE career_goals DISABLE ROW LEVEL SECURITY;
ALTER TABLE learning_progress DISABLE ROW LEVEL SECURITY;
ALTER TABLE applications DISABLE ROW LEVEL SECURITY;
ALTER TABLE resumes DISABLE ROW LEVEL SECURITY;
ALTER TABLE resume_analyses DISABLE ROW LEVEL SECURITY;
ALTER TABLE interviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE interview_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE interview_answers DISABLE ROW LEVEL SECURITY;
ALTER TABLE skill_gap_analysis DISABLE ROW LEVEL SECURITY;
ALTER TABLE skill_gap_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE recommendations DISABLE ROW LEVEL SECURITY;
ALTER TABLE agent_conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE agent_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE courses DISABLE ROW LEVEL SECURITY;
ALTER TABLE course_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE internships DISABLE ROW LEVEL SECURITY;

COMMIT;
